---
title: "OBAMA NEXT information products"
format: html
---

Information products developed.


### Coastal Vegetation Mapping Using Remote Sensing

High-resolution drone-based mapping of coastal vegetation, including _in situ_ ground truthing, model training, testing and validation.

Read more about this topic on [OBAMA NEXT project website](https://obama-next.eu/information-products/#CoastalVegetation).

[...link to repository to come](https://github.com/OBAMANEXT/)


### Habitat Suitability Modelling of Marine Mammals

Maps of habitat suitability and use for these marine mammal species can show how ecosystems respond to environmental change and the effectiveness of conservation actions.

Read more about this topic on [OBAMA NEXT project website](https://obama-next.eu/information-products/#MarineMammals).

* **IP18 - Porpoise SDM** - The code reads the harbour porpoise tracking data (based on ARGOS tags), cleans the Argos data, and performs a MaxEnt analyses to generate habitat suitability layers for one season and period (out of 6). Raster data is based on Copernicus data, which is freely available but also provided in the raster folder. To generate habitat suitability layers for all season and periods described in the article, adjust the code to the season and period of interest and rerun the procedure. See the code [here](https://github.com/OBAMANEXT/SDM_porpoise_IP18).


###  High-Resolution Predictive Maps of Processes Underlying Fish Reproduction

The model integrates different types of fisheries and survey data and returns estimates of how different processes underlying animal’s reproduction cycle are affected by environmental conditions at a local scale, as well as predictive maps of animal and underlying reproduction processes distribution along the area of interest. The model applies to the Baltic whitefish.  

Read more about this topic on [OBAMA NEXT project website](https://obama-next.eu/information-products/#FishReproduction).

[...link to repository to come](https://github.com/OBAMANEXT/)


###  Detecting and Quantifying Macroplastic on Beaches using Drones and AI

This IP describes how drones equipped with advanced sensors can be used to detect macroplastics on beaches. Artificial Intelligence is used to quantify the amount of litter, for instance before and after a beach clean-up event. The SeaBee drone infrastructure has done proof-of-concept studies on this, which still remains to be included in monitoring.

Read more about this topic on [OBAMA NEXT project website](https://obama-next.eu/information-products/#Macroplastics).

[...link to repository to come](https://github.com/OBAMANEXT/)
